name: Update FP (Joga/Kalistenika) ICS

on:
  schedule:
    - cron: "15 5 * * 1"
    - cron: "15 6 * * 1"
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FORCE_RUN: ${{ github.event_name == 'workflow_dispatch' && '1' || '0' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run scraper
        run: |
          python scrape_fp.py --out docs
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.ics docs/*.json docs/*.md docs/index.html || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update FP timetable (auto)"
            git push
          fi
      - name: Create Issue if something changed
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const read = (p)=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):null;
            const sum = read('docs/availability_summary.json');
            const loc = read('docs/changes.json');
            const ev  = read('docs/events_changes.json');
            const anyLoc = loc && ((loc.added||[]).length || (loc.removed||[]).length);
            const anyEv  = ev  && ((ev.added||[]).length  || (ev.removed||[]).length);
            if (!anyLoc && !anyEv) return;
            const title = `FP: zmiany joga/kalistenika (${(sum && sum.generated_at) || new Date().toISOString()})`;
            let body = '';
            if (loc) body += `**Lokalizacje:** +${(loc.added||[]).length} / -${(loc.removed||[]).length}\n`;
            if (ev)  body += `**Terminy:** +${(ev.added||[]).length} / -${(ev.removed||[]).length}\n\n`;
            if (loc) {
              body += `**Dodane lokalizacje:** ${(loc.added||[]).length ? loc.added.join(', ') : '(brak)'}\n`;
              body += `**Usunięte lokalizacje:** ${(loc.removed||[]).length ? loc.removed.join(', ') : '(brak)'}\n\n`;
            }
            if (ev) {
              const sample = (arr)=> (arr||[]).slice(0,20).map(x=>`- ${x}`).join('\n') || '- (brak)';
              body += `**Przykładowe nowe terminy (max 20):**\n${sample(ev.added)}\n\n`;
              body += `**Przykładowe usunięte terminy (max 20):**\n${sample(ev.removed)}\n\n`;
            }
            body += 'Szczegóły: docs/changes.md + docs/events_changes.json + docs/debug_calls.json';
            await github.rest.issues.create({owner: context.repo.owner, repo: context.repo.repo, title, body});
